Bhomik keshi

25070123172

Experiment 15

Data Normalization and Data Type Conversion

Part A Data Normalization

In [ ]:
import pandas as pd
import numpy as np
data = {
    'Product': ['Laptop', 'Mobile', 'Tablet', 'Headphones', 'Smartwatch', 'Camera'],
    'Price': [55000, 20000, 30000, 2000, 8000, 45000],
    'Units_Sold': [25, 60, 35, 80, 50, 15],
    'Discount':[10,15,12,20,18,8]
}
df = pd.DataFrame(data)
print(df)

      Product  Price  Units_Sold  Discount
0      Laptop  55000          25        10
1      Mobile  20000          60        15
2      Tablet  30000          35        12
3  Headphones   2000          80        20
4  Smartwatch   8000          50        18
5      Camera  45000          15         8

In [ ]:
#1.Min-Max Normalization
# Min-Max Normalization for price
df['Price_MinMax'] = (df['Price'] - df['Price'].min()) / (df['Price'].max() - df['Price'].min())
print(df[['Product', 'Price', 'Price_MinMax']])

      Product  Price  Price_MinMax
0      Laptop  55000      1.000000
1      Mobile  20000      0.339623
2      Tablet  30000      0.528302
3  Headphones   2000      0.000000
4  Smartwatch   8000      0.113208
5      Camera  45000      0.811321

In [ ]:
#1.Min-Max Normalization
# Min-Max Normalization for Discount
df['Discount_MinMax'] = (df['Discount'] - df['Discount'].min()) / (df['Discount'].max() - df['Discount'].min())
print(df[['Product', 'Discount', 'Discount_MinMax']])

      Product  Discount  Discount_MinMax
0      Laptop        10         0.166667
1      Mobile        15         0.583333
2      Tablet        12         0.333333
3  Headphones        20         1.000000
4  Smartwatch        18         0.833333
5      Camera         8         0.000000

In [ ]:
# #1.Min-Max Normalization
# Min-Max Normalization for Unit_Sold
df['Units_Sold_MinMax'] = (df['Units_Sold'] - df['Units_Sold'].min()) / (df['Units_Sold'].max() - df['Units_Sold'].min())
print(df[['Product', 'Units_Sold', 'Units_Sold_MinMax']])

      Product  Units_Sold  Units_Sold_MinMax
0      Laptop          25           0.153846
1      Mobile          60           0.692308
2      Tablet          35           0.307692
3  Headphones          80           1.000000
4  Smartwatch          50           0.538462
5      Camera          15           0.000000

In [ ]:
#Normalize Multiple Columns
colsd=['Price','Units_Sold','Discount']
df[colsd]=(df[colsd]-df[colsd].min())/(df[colsd].max()-df[colsd].min())
print(df)

      Product     Price  Units_Sold  Discount  Price_MinMax  Discount_MinMax  \
0      Laptop  1.000000    0.153846  0.166667      1.000000         0.166667
1      Mobile  0.339623    0.692308  0.583333      0.339623         0.583333
2      Tablet  0.528302    0.307692  0.333333      0.528302         0.333333
3  Headphones  0.000000    1.000000  1.000000      0.000000         1.000000
4  Smartwatch  0.113208    0.538462  0.833333      0.113208         0.833333
5      Camera  0.811321    0.000000  0.000000      0.811321         0.000000

   Units_Sold_MinMax
0           0.153846
1           0.692308
2           0.307692
3           1.000000
4           0.538462
5           0.000000

In [ ]:
#2.Z-score Normalization
df['Units_Sold_Zscore'] = (df['Units_Sold'] - df['Units_Sold'].mean()) / df['Units_Sold'].std()
print(df[['Product', 'Units_Sold', 'Units_Sold_Zscore']])

      Product  Units_Sold  Units_Sold_Zscore
0      Laptop    0.153846          -0.799885
1      Mobile    0.692308           0.660775
2      Tablet    0.307692          -0.382554
3  Headphones    1.000000           1.495437
4  Smartwatch    0.538462           0.243443
5      Camera    0.000000          -1.217216

In [ ]:
#3. Decimal Scaling
df['Price_Decimal'] = df['Price'].apply(lambda x: round(x, 2))
print(df[['Product', 'Price', 'Price_Decimal']])

      Product     Price  Price_Decimal
0      Laptop  1.000000           1.00
1      Mobile  0.339623           0.34
2      Tablet  0.528302           0.53
3  Headphones  0.000000           0.00
4  Smartwatch  0.113208           0.11
5      Camera  0.811321           0.81

In [ ]:
import pandas as pd
import numpy as np
data = {
'Order_ID':[101,102,103,104,105,106],
'Customer_Gender':['Male','Female','Female','Male','Female','Male'],
'Payment_Method':['UPI','Credit Card','Debit Card','COD','UPI','Debit Card'],
'Product_Category':['Electronics','Clothing','Home','Electronics','Beauty','Electronics'],
'City':['Pune','Mumbai','Delhi','Bangalore','Pune','Hyderabad'],
'Order_Value':[4500,2300,3200,5200,1800,4100]
}
df = pd.DataFrame(data)
print(df)

   Order_ID Customer_Gender Payment_Method Product_Category       City  \
0       101            Male            UPI      Electronics       Pune
1       102          Female    Credit Card         Clothing     Mumbai
2       103          Female     Debit Card             Home      Delhi
3       104            Male            COD      Electronics  Bangalore
4       105          Female            UPI           Beauty       Pune
5       106            Male     Debit Card      Electronics  Hyderabad

   Order_Value
0         4500
1         2300
2         3200
3         5200
4         1800
5         4100

In [ ]:
#Method 1:Label Encoding
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['Customer_Gender_Label']=le.fit_transform(df['Customer_Gender'])
#df['Payment_Method_Label']=le.fit_transform(df['Payment_Method'])
#df['Product_Category_Label']=le.fit_transform(df['Product_Category'])
df['City_Label']=le.fit_transform(df['City'])
df

,Order_ID,Customer_Gender,Payment_Method,Product_Category,City,Order_Value,Customer_Gender_Label,City_Label
0,101,Male,UPI,Electronics,Pune,4500,1,4
1,102,Female,Credit Card,Clothing,Mumbai,2300,0,3
2,103,Female,Debit Card,Home,Delhi,3200,0,1
3,104,Male,COD,Electronics,Bangalore,5200,1,0
4,105,Female,UPI,Beauty,Pune,1800,0,4
5,106,Male,Debit Card,Electronics,Hyderabad,4100,1,2

In [ ]:
#Method 2:One-Hot Encoding
df_encoded=pd.get_dummies(df,columns=['Payment_Method'])
display(df_encoded)

,Order_ID,Customer_Gender,Product_Category,City,Order_Value,Customer_Gender_Label,City_Label,Payment_Method_COD,Payment_Method_Credit Card,Payment_Method_Debit Card,Payment_Method_UPI
0,101,Male,Electronics,Pune,4500,1,4,False,False,False,True
1,102,Female,Clothing,Mumbai,2300,0,3,False,True,False,False
2,103,Female,Home,Delhi,3200,0,1,False,False,True,False
3,104,Male,Electronics,Bangalore,5200,1,0,True,False,False,False
4,105,Female,Beauty,Pune,1800,0,4,False,False,False,True
5,106,Male,Electronics,Hyderabad,4100,1,2,False,False,True,False

In [ ]:
 # Encoding Multiple Columns
 df_encoded=pd.get_dummies(df,columns=['Payment_Method','Product_Category','City'])
 display(df_encoded)

,Order_ID,Customer_Gender,Order_Value,Customer_Gender_Label,City_Label,Payment_Method_COD,Payment_Method_Credit Card,Payment_Method_Debit Card,Payment_Method_UPI,Product_Category_Beauty,Product_Category_Clothing,Product_Category_Electronics,Product_Category_Home,City_Bangalore,City_Delhi,City_Hyderabad,City_Mumbai,City_Pune
0,101,Male,4500,1,4,False,False,False,True,False,False,True,False,False,False,False,False,True
1,102,Female,2300,0,3,False,True,False,False,False,True,False,False,False,False,False,True,False
2,103,Female,3200,0,1,False,False,True,False,False,False,False,True,False,True,False,False,False
3,104,Male,5200,1,0,True,False,False,False,False,False,True,False,True,False,False,False,False
4,105,Female,1800,0,4,False,False,False,True,True,False,False,False,False,False,False,False,True
5,106,Male,4100,1,2,False,False,True,False,False,False,True,False,False,False,True,False,False

In [ ]:
#Method3:Dummy Encoding (Drop First)
df_encoded=pd.get_dummies(df,columns=['Payment_Method'],drop_first=True)
print(df_encoded)

   Order_ID Customer_Gender Product_Category       City  Order_Value  \
0       101            Male      Electronics       Pune         4500
1       102          Female         Clothing     Mumbai         2300
2       103          Female             Home      Delhi         3200
3       104            Male      Electronics  Bangalore         5200
4       105          Female           Beauty       Pune         1800
5       106            Male      Electronics  Hyderabad         4100

   Customer_Gender_Label  City_Label  Payment_Method_Credit Card  \
0                      1           4                       False
1                      0           3                        True
2                      0           1                       False
3                      1           0                       False
4                      0           4                       False
5                      1           2                       False

   Payment_Method_Debit Card  Payment_Method_UPI
0                      False                True
1                      False               False
2                       True               False
3                      False               False
4                      False                True
5                       True               False

In [ ]:
#Data Normalization
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler, StandardScaler

# Loading the dataset
df_amazon = pd.read_csv("/content/amazon_products_dataset_Expt-14.csv")

print(df_amazon)

   Product_ID                 Product_Name  Price  Rating  Reviews  Units_Sold
0        P101               Wireless Mouse    799     4.3     1520         350
1        P102            Bluetooth Speaker   1499     4.5      980         220
2        P103                 USB Keyboard    699     4.1      870         180
3        P104               Gaming Headset   2499     4.6     2100         410
4        P105                   Smartwatch   3999     4.4     3050         520
5        P106                   Power Bank   1199     4.2     1750         390
6        P107                 Laptop Stand    899     4.0      620         140
7        P108                       Webcam   1899     4.3     1120         260
8        P109                 Portable SSD   5499     4.7     1850         330
9        P110             Wireless Charger    999     4.2      760         190
10       P111  Noise Cancelling Headphones   7999     4.6     4200         610
11       P112          Mechanical Keyboard   4599     4.5     2100         290
12       P113                 Gaming Mouse   1599     4.4     1300         340
13       P114                 Tablet Stand    699     4.1      540         120
14       P115                      USB Hub    899     4.2      870         200
15       P116          External Hard Drive   6499     4.6     2300         310
16       P117            Smartphone Tripod   1199     4.3      760         210
17       P118              Laptop Backpack   1999     4.4     1600         420
18       P119            Bluetooth Earbuds   2999     4.5     3500         530
19       P120                LED Desk Lamp   1299     4.3      980         260
20       P121                 Phone Holder    499     4.0      420         150
21       P122            Wireless Keyboard   2499     4.4     1450         310
22       P123             Portable Monitor   8999     4.6     1250         170
23       P124                   Smart Plug    799     4.2      720         210
24       P125                  WiFi Router   3499     4.5     2100         390
25       P126              Graphics Tablet   4599     4.4      980         160
26       P127                   VR Headset  12999     4.7     3100         140
27       P128                   Microphone   2199     4.3     1300         270
28       P129             Smart Light Bulb    699     4.2      880         240
29       P130           Laptop Cooling Pad   1499     4.3      990         260
30       P131                Action Camera   9999     4.6     2100         200
31       P132               Smart Doorbell   5999     4.5     1750         180
32       P133              Streaming Stick   3499     4.4     2500         430
33       P134           Portable Projector  11999     4.6     1450         120
34       P135                 Gaming Chair  15999     4.7     2100          90
35       P136               Desk Organizer    599     4.1      450         160
36       P137              USB Flash Drive    799     4.2      900         320
37       P138       Phone Screen Protector    299     4.0      600         380
38       P139                Laptop Sleeve    999     4.3      720         210
39       P140           Wireless Presenter   1499     4.4      520         130
40       P141         Tablet Keyboard Case   2999     4.5      850         150
41       P142             Smart Thermostat  10999     4.6     1200         110
42       P143              Security Camera   4999     4.4     2100         260
43       P144                 Drone Camera  24999     4.7     1800          70
44       P145              Electric Kettle   1999     4.3     1400         310
45       P146                    Air Fryer   7999     4.6     2200         200
46       P147                 Robot Vacuum  18999     4.5     1650         120
47       P148                  Smart Scale   2499     4.4      980         170
48       P149          Digital Photo Frame   3499     4.3      870         150
49       P150                 Portable Fan    999     4.2      760         240

In [ ]:
#Min-Max Normalization (All)
# Formula: (x - min) / (max - min) -> Scales to [0, 1]
scaler_mm = MinMaxScaler()
df_minmax = pd.DataFrame(scaler_mm.fit_transform(df_amazon.select_dtypes(include=[np.number])),
                         columns=df_amazon.select_dtypes(include=[np.number]).columns)
print(df)

   Order_ID Customer_Gender Payment_Method Product_Category       City  \
0       101            Male            UPI      Electronics       Pune
1       102          Female    Credit Card         Clothing     Mumbai
2       103          Female     Debit Card             Home      Delhi
3       104            Male            COD      Electronics  Bangalore
4       105          Female            UPI           Beauty       Pune
5       106            Male     Debit Card      Electronics  Hyderabad

   Order_Value  Customer_Gender_Label  City_Label
0         4500                      1           4
1         2300                      0           3
2         3200                      0           1
3         5200                      1           0
4         1800                      0           4
5         4100                      1           2

In [ ]:
#Z-Score Normalization
# Formula: (x - mean) / std -> Centers at 0 with unit variance
scaler_z = StandardScaler()
df_zscore = pd.DataFrame(scaler_z.fit_transform(df_amazon.select_dtypes(include=[np.number])),
                         columns=df_amazon.select_dtypes(include=[np.number]).columns)
print(df_zscore)

       Price    Rating   Reviews  Units_Sold  Price_scaled
0  -0.699045 -0.425861  0.076714    0.820529     -0.699045
1  -0.562968  0.612824 -0.582928   -0.263503     -0.562968
2  -0.718485 -1.464545 -0.717300   -0.597052     -0.718485
3  -0.368573  1.132166  0.785218    1.320851     -0.368573
4  -0.076980  0.093482  1.945700    2.238109     -0.076980
5  -0.621287 -0.945203  0.357673    1.154077     -0.621287
6  -0.679606 -1.983887 -1.022690   -0.930600     -0.679606
7  -0.485210 -0.425861 -0.411910    0.070045     -0.485210
8   0.214612  1.651508  0.479829    0.653755      0.214612
9  -0.660166 -0.945203 -0.851671   -0.513664     -0.660166
10  0.700600  1.132166  3.350493    2.988593      0.700600
11  0.039657  0.612824  0.785218    0.320206      0.039657
12 -0.543529  0.093482 -0.192029    0.737142     -0.543529
13 -0.718485 -1.464545 -1.120414   -1.097374     -0.718485
14 -0.679606 -0.945203 -0.717300   -0.430277     -0.679606
15  0.409007  1.132166  1.029530    0.486981      0.409007
16 -0.621287 -0.425861 -0.851671   -0.346890     -0.621287
17 -0.465771  0.093482  0.174439    1.404239     -0.465771
18 -0.271376  0.612824  2.495402    2.321497     -0.271376
19 -0.601848 -0.425861 -0.582928    0.070045     -0.601848
20 -0.757364 -1.983887 -1.267001   -0.847213     -0.757364
21 -0.368573  0.093482 -0.008795    0.486981     -0.368573
22  0.894995  1.132166 -0.253107   -0.680439      0.894995
23 -0.699045 -0.945203 -0.900534   -0.346890     -0.699045
24 -0.174178  0.612824  0.785218    1.154077     -0.174178
25  0.039657  0.093482 -0.582928   -0.763826      0.039657
26  1.672576  1.651508  2.006778   -0.930600      1.672576
27 -0.426892 -0.425861 -0.192029    0.153432     -0.426892
28 -0.718485 -0.945203 -0.705084   -0.096729     -0.718485
29 -0.562968 -0.425861 -0.570713    0.070045     -0.562968
30  1.089391  1.132166  0.785218   -0.430277      1.089391
31  0.311810  0.612824  0.357673   -0.597052      0.311810
32 -0.174178  0.093482  1.273842    1.487626     -0.174178
33  1.478181  1.132166 -0.008795   -1.097374      1.478181
34  2.255762  1.651508  0.785218   -1.347535      2.255762
35 -0.737924 -1.464545 -1.230355   -0.763826     -0.737924
36 -0.699045 -0.945203 -0.680653    0.570368     -0.699045
37 -0.796243 -1.983887 -1.047121    1.070690     -0.796243
38 -0.660166 -0.425861 -0.900534   -0.346890     -0.660166
39 -0.562968  0.093482 -1.144845   -1.013987     -0.562968
40 -0.271376  0.612824 -0.741731   -0.847213     -0.271376
41  1.283786  1.132166 -0.314185   -1.180761      1.283786
42  0.117415  0.093482  0.785218    0.070045      0.117415
43  4.005319  1.651508  0.418751   -1.514310      4.005319
44 -0.465771 -0.425861 -0.069873    0.486981     -0.465771
45  0.700600  1.132166  0.907374   -0.430277      0.700600
46  2.838947  0.612824  0.235517   -1.097374      2.838947
47 -0.368573  0.093482 -0.582928   -0.680439     -0.368573
48 -0.174178 -0.425861 -0.717300   -0.847213     -0.174178
49 -0.660166 -0.945203 -0.851671   -0.096729     -0.660166

In [ ]:
#Decimal Scaling (Review/Price)
# Formula: x / 10^j (where j is the number of digits of the max absolute value)
def decimal_scaling(series):
    j = np.ceil(np.log10(series.abs().max()))
    return series / (10**j)

df_amazon['Price_scaled'] = decimal_scaling(df_amazon['Price']) # Replace 'price' with your actual column name
print(df_amazon)

   Product_ID                 Product_Name  Price  Rating  Reviews  \
0        P101               Wireless Mouse    799     4.3     1520
1        P102            Bluetooth Speaker   1499     4.5      980
2        P103                 USB Keyboard    699     4.1      870
3        P104               Gaming Headset   2499     4.6     2100
4        P105                   Smartwatch   3999     4.4     3050
5        P106                   Power Bank   1199     4.2     1750
6        P107                 Laptop Stand    899     4.0      620
7        P108                       Webcam   1899     4.3     1120
8        P109                 Portable SSD   5499     4.7     1850
9        P110             Wireless Charger    999     4.2      760
10       P111  Noise Cancelling Headphones   7999     4.6     4200
11       P112          Mechanical Keyboard   4599     4.5     2100
12       P113                 Gaming Mouse   1599     4.4     1300
13       P114                 Tablet Stand    699     4.1      540
14       P115                      USB Hub    899     4.2      870
15       P116          External Hard Drive   6499     4.6     2300
16       P117            Smartphone Tripod   1199     4.3      760
17       P118              Laptop Backpack   1999     4.4     1600
18       P119            Bluetooth Earbuds   2999     4.5     3500
19       P120                LED Desk Lamp   1299     4.3      980
20       P121                 Phone Holder    499     4.0      420
21       P122            Wireless Keyboard   2499     4.4     1450
22       P123             Portable Monitor   8999     4.6     1250
23       P124                   Smart Plug    799     4.2      720
24       P125                  WiFi Router   3499     4.5     2100
25       P126              Graphics Tablet   4599     4.4      980
26       P127                   VR Headset  12999     4.7     3100
27       P128                   Microphone   2199     4.3     1300
28       P129             Smart Light Bulb    699     4.2      880
29       P130           Laptop Cooling Pad   1499     4.3      990
30       P131                Action Camera   9999     4.6     2100
31       P132               Smart Doorbell   5999     4.5     1750
32       P133              Streaming Stick   3499     4.4     2500
33       P134           Portable Projector  11999     4.6     1450
34       P135                 Gaming Chair  15999     4.7     2100
35       P136               Desk Organizer    599     4.1      450
36       P137              USB Flash Drive    799     4.2      900
37       P138       Phone Screen Protector    299     4.0      600
38       P139                Laptop Sleeve    999     4.3      720
39       P140           Wireless Presenter   1499     4.4      520
40       P141         Tablet Keyboard Case   2999     4.5      850
41       P142             Smart Thermostat  10999     4.6     1200
42       P143              Security Camera   4999     4.4     2100
43       P144                 Drone Camera  24999     4.7     1800
44       P145              Electric Kettle   1999     4.3     1400
45       P146                    Air Fryer   7999     4.6     2200
46       P147                 Robot Vacuum  18999     4.5     1650
47       P148                  Smart Scale   2499     4.4      980
48       P149          Digital Photo Frame   3499     4.3      870
49       P150                 Portable Fan    999     4.2      760

    Units_Sold  Price_scaled
0          350       0.00799
1          220       0.01499
2          180       0.00699
3          410       0.02499
4          520       0.03999
5          390       0.01199
6          140       0.00899
7          260       0.01899
8          330       0.05499
9          190       0.00999
10         610       0.07999
11         290       0.04599
12         340       0.01599
13         120       0.00699
14         200       0.00899
15         310       0.06499
16         210       0.01199
17         420       0.01999
18         530       0.02999
19         260       0.01299
20         150       0.00499
21         310       0.02499
22         170       0.08999
23         210       0.00799
24         390       0.03499
25         160       0.04599
26         140       0.12999
27         270       0.02199
28         240       0.00699
29         260       0.01499
30         200       0.09999
31         180       0.05999
32         430       0.03499
33         120       0.11999
34          90       0.15999
35         160       0.00599
36         320       0.00799
37         380       0.00299
38         210       0.00999
39         130       0.01499
40         150       0.02999
41         110       0.10999
42         260       0.04999
43          70       0.24999
44         310       0.01999
45         200       0.07999
46         120       0.18999
47         170       0.02499
48         150       0.03499
49         240       0.00999

In [ ]:
#Turning categorical variable into quantitaive variable
df=pd.read_csv('/content/Student-Dataset.csv')
print(df)

   Roll_No  Gender  Department  CGPA  Number_of_Backlogs  \
0      101  Female    Computer   8.2                   0
1      102    Male          IT   7.5                   1
2      103  Female        ENTC   9.1                   0
3      104    Male  Mechanical   6.8                   2
4      105  Female    Computer   8.7                   0
5      106    Male       Civil   7.2                   3
6      107  Female          IT   8.9                   0
7      108    Male    Computer   6.5                   1
8      109  Female        ENTC   7.8                   0
9      110    Male  Mechanical   7.0                   2

   Attendance_Percentage Placement_Status  Salary
0                     92           Placed  450000
1                     85       Not Placed       0
2                     96           Placed  550000
3                     78       Not Placed       0
4                     88           Placed  480000
5                     72       Not Placed       0
6                     91           Placed  500000
7                     80       Not Placed       0
8                     84           Placed  420000
9                     76       Not Placed       0

In [ ]:
# Label Encoding (Placement Status)
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Placement_Status_Encoded'] = le.fit_transform(df['Placement_Status'])
print(df)

   Roll_No  Gender  Department  CGPA  Number_of_Backlogs  \
0      101  Female    Computer   8.2                   0
1      102    Male          IT   7.5                   1
2      103  Female        ENTC   9.1                   0
3      104    Male  Mechanical   6.8                   2
4      105  Female    Computer   8.7                   0
5      106    Male       Civil   7.2                   3
6      107  Female          IT   8.9                   0
7      108    Male    Computer   6.5                   1
8      109  Female        ENTC   7.8                   0
9      110    Male  Mechanical   7.0                   2

   Attendance_Percentage Placement_Status  Salary  Placement_Status_Encoded
0                     92           Placed  450000                         1
1                     85       Not Placed       0                         0
2                     96           Placed  550000                         1
3                     78       Not Placed       0                         0
4                     88           Placed  480000                         1
5                     72       Not Placed       0                         0
6                     91           Placed  500000                         1
7                     80       Not Placed       0                         0
8                     84           Placed  420000                         1
9                     76       Not Placed       0                         0

In [ ]:
# One Hot Encoding (Department)

from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(sparse_output=False)
dept_encoded = ohe.fit_transform(df[['Department']])
dept_df = pd.DataFrame(dept_encoded, columns=ohe.get_feature_names_out(['Department']))
df_final = pd.concat([df, dept_df], axis=1)
print(df_final)

   Roll_No  Gender  Department  CGPA  Number_of_Backlogs  \
0      101  Female    Computer   8.2                   0
1      102    Male          IT   7.5                   1
2      103  Female        ENTC   9.1                   0
3      104    Male  Mechanical   6.8                   2
4      105  Female    Computer   8.7                   0
5      106    Male       Civil   7.2                   3
6      107  Female          IT   8.9                   0
7      108    Male    Computer   6.5                   1
8      109  Female        ENTC   7.8                   0
9      110    Male  Mechanical   7.0                   2

   Attendance_Percentage Placement_Status  Salary  Placement_Status_Encoded  \
0                     92           Placed  450000                         1
1                     85       Not Placed       0                         0
2                     96           Placed  550000                         1
3                     78       Not Placed       0                         0
4                     88           Placed  480000                         1
5                     72       Not Placed       0                         0
6                     91           Placed  500000                         1
7                     80       Not Placed       0                         0
8                     84           Placed  420000                         1
9                     76       Not Placed       0                         0

   Department_Civil  Department_Computer  Department_ENTC  Department_IT  \
0               0.0                  1.0              0.0            0.0
1               0.0                  0.0              0.0            1.0
2               0.0                  0.0              1.0            0.0
3               0.0                  0.0              0.0            0.0
4               0.0                  1.0              0.0            0.0
5               1.0                  0.0              0.0            0.0
6               0.0                  0.0              0.0            1.0
7               0.0                  1.0              0.0            0.0
8               0.0                  0.0              1.0            0.0
9               0.0                  0.0              0.0            0.0

   Department_Mechanical
0                    0.0
1                    0.0
2                    0.0
3                    1.0
4                    0.0
5                    0.0
6                    0.0
7                    0.0
8                    0.0
9                    1.0

In [ ]:
# Dummies (Department)

df_dummies = pd.get_dummies(df, columns=['Department'])
print(df_dummies)

   Roll_No  Gender  CGPA  Number_of_Backlogs  Attendance_Percentage  \
0      101  Female   8.2                   0                     92
1      102    Male   7.5                   1                     85
2      103  Female   9.1                   0                     96
3      104    Male   6.8                   2                     78
4      105  Female   8.7                   0                     88
5      106    Male   7.2                   3                     72
6      107  Female   8.9                   0                     91
7      108    Male   6.5                   1                     80
8      109  Female   7.8                   0                     84
9      110    Male   7.0                   2                     76

  Placement_Status  Salary  Placement_Status_Encoded  Department_Civil  \
0           Placed  450000                         1             False
1       Not Placed       0                         0             False
2           Placed  550000                         1             False
3       Not Placed       0                         0             False
4           Placed  480000                         1             False
5       Not Placed       0                         0              True
6           Placed  500000                         1             False
7       Not Placed       0                         0             False
8           Placed  420000                         1             False
9       Not Placed       0                         0             False

   Department_Computer  Department_ENTC  Department_IT  Department_Mechanical
0                 True            False          False                  False
1                False            False           True                  False
2                False             True          False                  False
3                False            False          False                   True
4                 True            False          False                  False
5                False            False          False                  False
6                False            False           True                  False
7                 True            False          False                  False
8                False             True          False                  False
9                False            False          False                   True